title: "Preparation Hub"
description: "Mahesh's Personal Preparation Notes — DSA, System Design, Cloud, and more."
theme: jekyll-theme-cayman
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - preparation
